### ISSUE TITLE
Usage Documentation

### ISSUE THREAD

**Issue by chukcha2** [amurchick/AudioBooksDownload#2]
Could someone add some basic instructions to README.md on how to use these scripts?
Thank you.

**Comment by amurchick** [comment]
Updated docs at c338e1d

**Comment by chukcha2** [comment]
Thank you for the update. I just got a chance to try it now. I get the following error. I am sure that is most likely because I don't know anything about js/node. Could you please let me know how to resolve this issue, or update the usage documentation. Thank you.

> node index https://audioknigi.club/elton-ben-dva-brata
> /home/ilya/tmp/AudioBooksDownload/index.js:6
> let jsdom = require('jsdom');
> ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:442:10)
>     at startup (node.js:136:18)
>     at node.js:966:3

**Comment by amurchick** [comment]
Please update your `node` version.
Command `node -v` must display version 4.3.2 or later.
