### ISSUE TITLE
Some problems with folder name that has slash

### ISSUE THREAD

**Issue by chmelvv** [amurchick/AudioBooksDownload#4]
node index https://audioknigi.club/heinlein-robert-haynlayn-robert-tunnel-in-the-sky-tunnel-v-nebe-audiokniga_eng
Downloading https://audioknigi.club/heinlein-robert-haynlayn-robert-tunnel-in-the-sky-tunnel-v-nebe-audiokniga_eng...
Download "http://audioknigi.club/rest/bid/14332"...
Title: Хайнлайн Роберт - Tunnel in the Sky / Туннель в небе (ENG)
Image: https://audioknigi.club/uploads/topics/preview/00/00/20/91/02a5325ae9.jpg
Tracks: 91
processFunction() error Error: ENOENT: no such file or directory, mkdir 'C:\audiobook\AudioBooksDownload\Хайнлайн Роберт - Tunnel in the Sky \ Туннель в небе (ENG)'
    at Object.fs.mkdirSync (fs.js:890:18)
    at processFunction (C:\audiobook\AudioBooksDownload\index.js:172:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by amurchick** [comment]
Thank you for report!

Fixed in 2.0.1 https://github.com/amurchick/AudioBooksDownload/releases/tag/2.0.1
